# Generated by Django 3.0.7 on 2020-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_closed',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='master',
            field=models.ManyToManyField(blank=True, default=None, related_name='master', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, default=None, related_name='players', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='attempts',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='session_id',
            field=models.TextField(blank=True, default=None),
        ),
    ]
