# Generated by Django 3.0.7 on 2020-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200627_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
