# Generated by Django 3.0.8 on 2020-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200627_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_closed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
