# Generated by Django 3.0.8 on 2020-07-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='master',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.Player'),
        ),
    ]
